on: pull_request
name: Clippy Annotations
jobs:
  clippy_annotations:
  if: "!contains(github.event.head_commit.message, '[clippy skip]') && !contains(github.event.head_commit.message, '[skip clippy]'"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features