name: Continous Integration

on:
  push:
  pull_request:

jobs:
  build:
    name: Linux Rust Build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build on Linux
        run: cargo build --verbose
      - name: Run Tests
        run: cargo test --verbose