name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Rust Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose