name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
if: "!contains(github.event.head_commit.message, '[build skip]') && !contains(github.event.head_commit.message, '[skip build]'"
  jobs:
    build:
      runs-on: ubuntu-18.04

      steps:
      - uses: actions/checkout@v2
      - name: Build
      run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose